name: in_my_lane
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0 # Add this line for the date formatting functionality
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
     - assets/logolady.png
     - assets/background.png
     - assets/s38.png
     - assets/2_19.png
     - assets/s15.png
     - assets/2_42.png
     - assets/s1.png
     - assets/s24.png
     - assets/s30.png
     - assets/s32.png
     - assets/s40.png 
     - assets/s44.png
     - assets/arrow_back.png
     - assets/home.png