// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nfclKRDV0xStilIGApD-lCXbyOSQ0RM',
    appId: '1:838400646292:web:2e8264b6d2e44a0fee6881',
    messagingSenderId: '838400646292',
    projectId: 'in-my-lane-app',
    authDomain: 'in-my-lane-app.firebaseapp.com',
    storageBucket: 'in-my-lane-app.appspot.com',
    measurementId: 'G-LGGBZHZ3G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjLqqbczQ6aELSwBa_6jeOsk5QeRS_wMw',
    appId: '1:838400646292:android:37868163cf341437ee6881',
    messagingSenderId: '838400646292',
    projectId: 'in-my-lane-app',
    storageBucket: 'in-my-lane-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Nt9KVLMMxG5XxFxkgJPVIGusJj0N05U',
    appId: '1:838400646292:ios:ffbe9c3ec78bc05bee6881',
    messagingSenderId: '838400646292',
    projectId: 'in-my-lane-app',
    storageBucket: 'in-my-lane-app.appspot.com',
    iosClientId: '838400646292-ke3mhhdl62tiebmpnjlmgm5fdi59n3ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Nt9KVLMMxG5XxFxkgJPVIGusJj0N05U',
    appId: '1:838400646292:ios:ffbe9c3ec78bc05bee6881',
    messagingSenderId: '838400646292',
    projectId: 'in-my-lane-app',
    storageBucket: 'in-my-lane-app.appspot.com',
    iosClientId: '838400646292-ke3mhhdl62tiebmpnjlmgm5fdi59n3ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6nfclKRDV0xStilIGApD-lCXbyOSQ0RM',
    appId: '1:838400646292:web:f520d7b675aefcd0ee6881',
    messagingSenderId: '838400646292',
    projectId: 'in-my-lane-app',
    authDomain: 'in-my-lane-app.firebaseapp.com',
    storageBucket: 'in-my-lane-app.appspot.com',
    measurementId: 'G-B8C4HVJH4T',
  );
}
